# Generated by Django 6.0.3 on 2026-07-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodetalle',
            name='cantidad_paquetes',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='costo_por_paquete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='unidades_por_paquete',
            field=models.IntegerField(default=1),
        ),
    ]
