# Generated by Django 6.0.3 on 2026-07-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientodetalle',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientodetalle',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='movimientodetalle',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='movimientodetalle',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientodetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='modificado_por',
        ),
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='capacidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Capacidad por unidad (Ej: 750)'),
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='MovimientoDetalle',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
    ]
